version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  api:
    build:
      context: api
      dockerfile: ./Dockerfile
      args:
        - APP_USER_UID=${APP_USER_UID}
        - APP_GROUP_GID=${APP_GROUP_GID}
        - APP_USER=${APP_USER}
        - APP_GROUP=${APP_GROUP}
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./api:/opt/myapp/
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true
  web:
    container_name: web
    build:
      context: web
      dockerfile: ./Dockerfile
      args:
        - APP_USER_UID=${APP_USER_UID}
        - APP_GROUP_GID=${APP_GROUP_GID}
        - APP_USER=${APP_USER}
        - APP_GROUP=${APP_GROUP}
    volumes:
      - ./web:/opt/myapp
    command: sh -c "yarn start"
    ports:
      - "3001:3001"
    depends_on:
      - api
volumes:
  db: